import Head from "next/head";
import { useGetTodosQuery } from "@/api/todos";
import { TodoInterface } from "@/store/todosSlice";
import { Todo } from "@/components/Todo/Todo";
import { AddTodoForm } from "@/components/AddTodoForm/AddTodoForm";

export default function Home() {
  const { data, isLoading } = useGetTodosQuery({});

  if (isLoading) {
    return <div>Loading...</div>;
  }

  return (
    <>
      <Head>
        <title>Todo app RTK</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <AddTodoForm />
        <div className="flex flex-col gap-1">
          {data &&
            data.map((todo: TodoInterface) => (
              <Todo todo={todo} key={todo.id} />
            ))}
        </div>
      </div>
    </>
  );
}
